const CACHE="bogey-banter-v7-rc1-2-mayhem-final";
const FILES=["./","./index.html","./styles.css","./manifest.json","./firebase-config.js","./qrcode-local.js","./src/main.js","./src/config.js","./src/utils.js","./src/store.js","./src/firebase-service.js","./src/demo-service.js","./assets/splash-characters-approved.jpeg","./assets/cards/card-001.jpg","./assets/cards/card-002.jpg","./assets/cards/card-003.jpg","./assets/cards/card-004.jpg","./assets/cards/card-005.jpg","./assets/cards/card-006.jpg","./assets/cards/card-007.jpg","./assets/cards/card-008.jpg","./assets/cards/card-009.jpg","./assets/cards/card-010.jpg","./assets/cards/card-011.jpg","./assets/cards/card-012.jpg","./assets/cards/card-013.jpg","./assets/cards/card-014.jpg","./assets/cards/card-015.jpg","./assets/cards/card-016.jpg","./assets/cards/card-017.jpg","./assets/cards/card-018.jpg","./assets/cards/card-019.jpg","./assets/cards/card-020.jpg","./assets/cards/card-021.jpg","./assets/cards/card-022.jpg","./assets/cards/card-023.jpg","./assets/cards/card-024.jpg","./assets/cards/card-025.jpg","./assets/cards/card-026.jpg","./assets/cards/card-027.jpg","./assets/cards/card-028.jpg","./assets/cards/card-029.jpg","./assets/cards/card-030.jpg","./assets/cards/card-031.jpg","./assets/cards/card-032.jpg","./assets/cards/card-033.jpg","./assets/cards/card-034.jpg","./assets/cards/card-035.jpg","./assets/cards/card-036.jpg","./assets/cards/card-037.jpg","./assets/cards/card-038.jpg","./assets/cards/card-039.jpg","./assets/cards/card-040.jpg","./assets/cards/card-041.jpg","./assets/cards/card-042.jpg","./assets/cards/card-043.jpg","./assets/cards/card-044.jpg","./assets/cards/card-045.jpg","./assets/cards/card-046.jpg","./assets/cards/card-047.jpg","./assets/cards/card-048.jpg","./assets/cards/card-049.jpg","./assets/cards/card-050.jpg","./assets/cards/card-051.jpg","./assets/cards/card-052.jpg","./assets/cards/card-053.jpg","./assets/cards/card-054.jpg","./assets/cards/card-055.jpg","./assets/cards/card-056.jpg","./assets/cards/card-057.jpg","./assets/cards/card-058.jpg","./assets/cards/card-059.jpg","./assets/cards/card-060.jpg","./assets/backgrounds/home.jpg","./assets/backgrounds/create.jpg","./assets/backgrounds/join.jpg","./assets/backgrounds/lobby.jpg","./assets/backgrounds/draw.jpg","./assets/backgrounds/score.jpg","./assets/backgrounds/board.jpg","./assets/backgrounds/story.jpg","./assets/backgrounds/awards.jpg","./assets/backgrounds/beer.jpg","./assets/backgrounds/more.jpg"];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{
  if(e.request.method!=="GET")return;
  if(e.request.mode==="navigate"){e.respondWith(fetch(e.request).catch(()=>caches.match("./index.html")));return}
  e.respondWith(caches.match(e.request).then(cached=>cached||fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy))}return r})));
});
