export const TEAM_NAMES = [
  "The Bogey Boys",
  "Fairway Fiends",
  "Grip It & Sip It",
  "The Tree Magnets",
  "Sandbaggers Anonymous",
  "The Shank Redemption",
  "Fore Play Specialists",
  "Beerway Bandits",
  "Par-Tee Animals",
  "Pin Seekers",
  "Lost Ball Legends",
  "The Three-Putt Club"
];

export const AWARDS = [
  "Beer Champion",
  "Chaos King",
  "Biggest Choke",
  "Sand Specialist",
  "Tree Magnet",
  "Best Banter",
  "Court Jester",
  "MVP"
];

// [title, category, icon, one-hole rule, artKey, quote, number]
export const CHAOS_CARDS = [
["Tree Hugger", "Challenge", "🌳", "Before anyone tees off, one nominated player must hug a tree.", "card-001", "Trees need mates too.", 1],
["Foot Wedge", "Lucky Break", "👟", "Move the chosen ball one shoe length using only your foot, no closer to the hole.", "card-002", "Nobody saw that… right?", 2],
["One Club Only", "Sabotage", "1️⃣", "Choose one club and use only that club for this hole.", "card-003", "Choose wisely.", 3],
["Timber!", "Challenge", "🪵", "Everyone must yell “TIMBER!” immediately after every drive.", "card-004", "Warn the wildlife.", 4],
["Shotgun a Beer", "Beer Card", "🍺", "Everyone on the team drinks before teeing off.", "card-005", "Hydration comes first.", 5],
["Blind Putt", "Challenge", "🙈", "One nominated putt must be taken with eyes closed while teammates line it up.", "card-006", "Trust the line.", 6],
["Dizzy Driver", "Challenge", "🌀", "Spin around five times, then immediately hit the tee shot.", "card-007", "Straight is just a suggestion.", 7],
["Bag Swap", "Sabotage", "🎒", "Swap golf bags with the paired opponent for this hole.", "card-008", "Hope you know their clubs.", 8],
["Bunker Tax", "Sabotage", "🏖️", "Each bunker visit adds one stroke to this hole.", "card-009", "Welcome to the beach.", 9],
["Compliment Club", "Social", "💬", "Before every shot, compliment a player from the opposing team.", "card-010", "Be nice for once.", 10],
["Mulligan Mayhem", "Lucky Break", "✨", "Replay one shot on this hole with no penalty.", "card-011", "Pretend it never happened.", 11],
["Lefty Loosey", "Challenge", "🫲", "Play every shot opposite-handed for this hole.", "card-012", "Everything feels wrong.", 12],
["Lucky Bounce", "Lucky Break", "🍀", "Move the chosen ball one club length after one unlucky bounce.", "card-013", "The golf gods owe you.", 13],
["Pin Hunter", "Challenge", "🎯", "Nominate one tee shot. If it misses the green, add one stroke.", "card-014", "Pressure makes diamonds.", 14],
["Last Can Standing", "Beer Card", "🥫", "Nominate one player to finish their drink before the team holes out.", "card-015", "No sip left behind.", 15],
["Cheers Mate", "Beer Card", "🥂", "The team must cheers before every putt on this hole.", "card-016", "Raise it before you sink it.", 16],
["Putter Challenge", "Challenge", "🥄", "Use the putter for every shot after the tee shot.", "card-017", "Putter power.", 17],
["Leaf Blower", "Challenge", "🍃", "Before putting, wave your hat to clear the imaginary leaves.", "card-018", "Greenkeeping on a budget.", 18],
["Driver Only", "Sabotage", "🏌️", "Use only the driver for every shot on this hole.", "card-019", "Even on the green.", 19],
["Dizzy Driver XL", "Legendary", "💫", "Every player spins five times before every shot on this hole.", "card-020", "Maximum dizziness.", 20],
["Not My Shot", "Sabotage", "👉", "The paired opponent chooses which player takes your next shot.", "card-021", "Choose your victim.", 21],
["H2O", "Beer Card", "💧", "Everyone takes a drink before the tee shot and after the final putt.", "card-022", "Stay hydrated.", 22],
["Spin & Drive", "Challenge", "🌪️", "One nominated player spins five times before taking the drive.", "card-023", "Find the fairway somehow.", 23],
["Backwards Putt", "Challenge", "🔄", "One nominated putt must be taken facing away from the hole.", "card-024", "Eyes on everything but the cup.", 24],
["Bunker Shot", "Challenge", "⛱️", "If you enter a bunker, the next shot must be played one-handed.", "card-025", "The beach fights back.", 25],
["Club Swap", "Sabotage", "🔁", "Swap one club with the paired opponent for this hole.", "card-026", "Trade carefully.", 26],
["City Slicker", "Challenge", "🏙️", "One player must wear the team towel like a tie for the whole hole.", "card-027", "Dress for success.", 27],
["Bunker Water", "Beer Card", "🥤", "If your ball enters a bunker, take one drink before playing out.", "card-028", "Sand and sip.", 28],
["Drink Relay", "Beer Card", "🍻", "Each player takes one sip in batting order before the tee shot.", "card-029", "Pass the pressure.", 29],
["Secret Score", "Social", "🤐", "Do not say your score aloud until every team has submitted.", "card-030", "Keep them guessing.", 30],
["Pin Pointer", "Challenge", "📍", "A teammate must point at the flag throughout the nominated tee shot.", "card-031", "Helpful or hopeless?", 31],
["Beer Run", "Beer Card", "🏃", "Nominate one player to collect the team drinks before anyone tees off.", "card-032", "Priorities first.", 32],
["Ocean Drive", "Challenge", "🌊", "The drive must be aimed away from the nearest water hazard.", "card-033", "Fear the splash.", 33],
["Club Trade", "Sabotage", "🤝", "Trade one chosen club with another team until the hole is complete.", "card-034", "No refunds.", 34],
["Hat Stack", "Social", "🧢", "Stack every available team hat on one player for the tee shot.", "card-035", "Peak fashion.", 35],
["Beer Before", "Beer Card", "🍺", "Take one drink immediately before every team shot.", "card-036", "Swing oil activated.", 36],
["Wedge Only", "Sabotage", "🔺", "Use wedges only after the tee shot.", "card-037", "Loft is life.", 37],
["Photo Finish", "Social", "📸", "Take a full-team photo before the final putt.", "card-038", "Proof of the chaos.", 38],
["Long Drive", "Challenge", "🚀", "Choose one player to take two drives and use the longer one.", "card-039", "Send it.", 39],
["Shot After Shot", "Beer Card", "🥃", "Take one drink immediately after each completed team shot.", "card-040", "Recovery fuel.", 40],
["All at Once", "Challenge", "💥", "All players tee off together after a countdown.", "card-041", "Controlled chaos.", 41],
["Stone Skip", "Challenge", "🪨", "Before the tee shot, mime skipping a stone across water.", "card-042", "Technique matters.", 42],
["Animal Style", "Social", "🐒", "Choose an animal; every celebration must imitate it this hole.", "card-043", "Release your inner beast.", 43],
["Sand Dance", "Social", "💃", "If anyone enters a bunker, the team performs a five-second dance.", "card-044", "Dance at the beach.", 44],
["Gimme Gate", "Lucky Break", "🎁", "One putt inside one standard putter length counts as holed.", "card-045", "Close enough.", 45],
["Free Hand", "Challenge", "✋", "One nominated shot must be played one-handed.", "card-046", "One hand, no excuses.", 46],
["Caddy Chat", "Social", "🗣️", "One player must act as an overconfident caddy for every shot.", "card-047", "Trust the expert.", 47],
["Personal Foul", "Social", "❓", "Before teeing off, answer one harmless question chosen by the other team.", "card-048", "No dodging.", 48],
["Island Rules", "Sabotage", "🏝️", "If the ball leaves the fairway, add one stroke.", "card-049", "Stay on the island.", 49],
["End of Road", "Beer Card", "🛣️", "The player with the worst shot takes one drink after the hole.", "card-050", "A rough finish.", 50],
["Fair Exchange", "Sabotage", "⚖️", "Swap the chosen ball position with the paired opponent once this hole.", "card-051", "Fair is questionable.", 51],
["Crew Swing", "Challenge", "👥", "Every player must copy the first player’s practice swing.", "card-052", "Follow the leader.", 52],
["Walk on Water", "Challenge", "🚶", "If a ball enters water, the player must walk ten steps carrying the club overhead.", "card-053", "Walk of shame.", 53],
["Compliment Captain", "Social", "🫡", "The team captain must compliment every player before teeing off.", "card-054", "Leadership matters.", 54],
["Cart Clean-Up", "Social", "🧹", "Collect all loose rubbish from the cart before the team tees off.", "card-055", "Leave no can behind.", 55],
["Team Selfie", "Social", "🤳", "Take a team selfie before the first shot.", "card-056", "Smile before the shank.", 56],
["One-Handed Sip", "Beer Card", "🥤", "Hold your drink in your non-dominant hand during the nominated tee shot.", "card-057", "Do not spill.", 57],
["Sidecar", "Challenge", "🛺", "One teammate must stand beside the player and give silent directions during one shot.", "card-058", "Back-seat golfing.", 58],
["Double Trouble", "Legendary", "⚡", "Draw one additional non-Legendary Chaos Card. Both effects apply this hole.", "card-059", "Twice the trouble.", 59],
["Chaos Combo", "Legendary", "🌪️", "Draw two additional Chaos Cards. All three effects apply this hole only.", "card-060", "Buckle up… maximum chaos incoming.", 60]
];

export const DEMO_NAMES=["Dennis","Jared","Tristen","Jak"];
export const CARD_CATEGORIES={"Lucky Break": {"className": "lucky"}, "Beer Card": {"className": "beer"}, "Challenge": {"className": "challenge"}, "Sabotage": {"className": "sabotage"}, "Social": {"className": "social"}, "Legendary": {"className": "legendary"}};
